import { ApiProperty } from "@nestjs/swagger";
import { IsDate, IsInt, IsNotEmpty, IsNumber, Max, Min } from "class-validator";

export class UpdateSpacedRepetitionCardDto {
  @ApiProperty({
    description: "An integer from 0-5 that indicates how easily the information was remembered, with 0 being most difficult",
    example: 3,
    minimum: 0,
    maximum: 5
  })
  @Min(0)
  @Max(5)
  @IsInt()
  @IsNotEmpty()
    quality: number;

  @ApiProperty({
    description: "An integer, indicating the number of repetitions that the card has been reviewed",
    example: 5,
    minimum: 0
  })
  @IsInt()
  @Min(0)
  @IsNotEmpty()
    repetitions: number;

  @ApiProperty({
    description: "A float that is generated by the SM2 algorithm, used to determine number of days between review",
    example: 2.5,
    minimum: 1.3
  })
  @IsNumber()
  @Min(1.3)
  @IsNotEmpty()
    easeFactor: number;

  @ApiProperty({
    description: "When the spaced repetition card is next due",
    example: 2.5,
    minimum: 1.3
  })
  @IsDate()
  @IsNotEmpty()
    due: Date;
}
