import { ApiProperty } from "@nestjs/swagger";
import { IsDate, IsInt, IsNumber, IsOptional, Min } from "class-validator";

export class UpdateSpacedRepetitionCardDto {
  @ApiProperty({
    description: "An integer, indicating the number of repetitions that the card has been reviewed",
    example: 5,
    required: false,
    minimum: 0
  })
  @IsInt()
  @Min(0)
  @IsOptional()
    repetitions?: number;

  @ApiProperty({
    description: "A float that is generated by the SM2 algorithm, used to determine number of days between review",
    example: 2.5,
    required: false,
    minimum: 1.3
  })
  @IsNumber()
  @Min(1.3)
  @IsOptional()
    easeFactor?: number;

  @ApiProperty({
    description: "When the spaced repetition card is next due",
    example: 2.5,
    required: false,
    minimum: 1.3
  })
  @IsDate()
  @IsOptional()
    due?: Date;
}
